# Generated by Django 3.1.1 on 2024-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20240307_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/captcha')),
            ],
        ),
    ]
